# -*- coding: utf-8 -*-
"""twitter_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSM2LbPVAMTc-j6tpsvLYf-z0d_UTgB8

# Getting the data you need
"""

import csv
import sys

csv.field_size_limit(sys.maxsize)

!pip install colabcode

from colabcode import ColabCode

ColabCode(port=10000)

! unzip stockerbot-export.zip

file = open('stockerbot-export-1.csv')
type(file)
csvreader = csv.reader(file)

header = []
header = next(csvreader)
print(header)

rows = []
for row in csvreader:
        rows.append(row)

company_name = "Dollar Tree"
company_tweets = []
for tweets in rows:
  if tweets[5] == company_name:
    company_tweets.append(tweets[1])

for x in range(len(company_tweets)):
    print(company_tweets[x])



"""# ML"""

!pip install -q transformers

# Using pipeline class to make predictions from models available in the Hub in an easy way 
from transformers import pipeline
specific_model = pipeline(model="finiteautomata/bertweet-base-sentiment-analysis")
list1 = specific_model(company_tweets)

list2 = []

for t in list1:
  list2.append(t['label'])

list2

list3 = []
for x in list2:
  if x == "POS":
    list3.append(1.0)
  elif x == "NEU":
    list3.append(0.5)
  elif x == "NEG":
    list3.append(0.0)

list3

def Average(lst):
    return sum(lst) / len(lst)

ticker_value = Average(list3)

